# Generated by Django 5.1.6 on 2025-03-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = []
